services:
  namenode:
    image: ${REGISTRY}/hadoop/hdfs
    restart: unless-stopped
    volumes:
      - hdfs_data:/home/hadoop/var
      - ${LOCALDATA}/hadoop:/home/hadoop/config
    command: namenode
    networks:
      - analytics-micro-net
    depends_on:
      - datanode
    expose:
      - "9000"
      - "8020"
  
  datanode:
    image: ${REGISTRY}/hadoop/hdfs
    restart: unless-stopped
    volumes:
      - hdfs_data:/home/hadoop/var
    command: datanode
    networks:
      - analytics-micro-net
    expose:
      - "9866"
      - "9000"

  hive-server:
    image: ${REGISTRY}/hadoop/hive-server
    restart: unless-stopped
    volumes:
      - hdfs_data:/home/hadoop/var
    command: datanode
    env_file:
      - conf/analytics.env
    networks:
      - analytics-micro-net
    expose:
      - "9866"
      - "9000"

  spark:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - analytics-micro-net
    depends_on:
      - spark-worker

  spark-worker:
    image: docker.io/bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - analytics-micro-net
    
  pipeline:
    image: ${REGISTRY}/hadoop/pipeline:latest
    volumes:
      - ${LOCALDATA}/tracking-logs:/var/tracking-logs:ro
    env_file:
      - conf/analytics.env
    depends_on:
      - namenode
      - spark
      - hive-server
    networks:
      - analytics-micro-net

volumes:
  hdfs_data:
