version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:1.5.2
    environment:
      - cluster.name=analyticstack
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - TAKE_FILE_OWNERSHIP=1
    restart: unless-stopped
    expose:
      - "9200"
      - "9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - analytics-micro-net

  nginx:
    image: ${REGISTRY}/web/nginx
    restart: unless-stopped
    volumes:
      - ${LOCALDATA}/nginx/conf.d:/etc/nginx/nginx.conf.d
    ports:
      - "80:80"
    networks:
      - analytics-micro-net

  mysql:
    image: ${REGISTRY}/web/mysql
    restart: unless-stopped
    env_file:
      - conf/mysql.env
      - conf/analytics.env
      - conf/pipeline.env
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - analytics-micro-net
  
  analytics-api:
    image: ${REGISTRY}/openedx/api
    restart: unless-stopped
    volumes:
      - openedx_marker:/home/openedx/marker
    env_file:
      - conf/analytics.env
    networks:
      - analytics-micro-net
    depends_on:
      - mysql
      - elasticsearch

  insights:
    image: ${REGISTRY}/openedx/insights
    restart: unless-stopped
    env_file:
      - conf/analytics.env
    volumes:
      - openedx_marker:/home/openedx/marker
    networks:
      - analytics-micro-net
    depends_on:
      - mysql
      - analytics-api
  
  db-worker:
    image: ${REGISTRY}/openedx/database-worker
    env_file:
      - conf/analytics.env
      - conf/mysql.env
    volumes:
      - openedx_marker:/home/openedx/marker
    networks:
      - analytics-micro-net
    depends_on:
      - mysql

volumes:
  elasticsearch_data:
  mysql_data:
  openedx_marker:
  insights_static:
  api_static:

networks:
  analytics-micro-net:
