version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:1.5.2
    environment:
      - cluster.name=analyticstack
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - TAKE_FILE_OWNERSHIP=1
    restart: unless-stopped
    expose:
      - "9200"
      - "9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - analytics-micro-net

  nginx:
    image: ${REGISTRY}/web/nginx
    volumes:
      - ${LOCALDATA}/nginx/conf.d:/etc/nginx/nginx.conf.d
    ports:
      - "80:80"
    networks:
      - analytics-micro-net

  mysql:
    image: ${REGISTRY}/web/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - analytics-micro-net
  
  analytics-api:
    image: ${REGISTRY}/openedx/api
    volumes:
      - openedx_marker:/home/openedx/marker
    networks:
      - analytics-micro-net

  insights:
    image: ${REGISTRY}/openedx/insights
    volumes:
      - openedx_marker:/home/openedx/marker
    networks:
      - analytics-micro-net
  
  db-worker:
    image: ${REGISTRY}/openedx/database-worker
    volumes:
      - openedx_marker:/home/openedx/marker
    networks:
      - analytics-micro-net

volumes:
  elasticsearch_data:
  mysql_data:
  openedx_marker:
  insights_static:
  api_static:

networks:
  analytics-micro-net:
