#!/bin/bash

set -ex

source "${EDX_VENV}"/bin/activate

dockerize -template "${CFG_FILE}".template:"${CFG_FILE}"

migrate_marker="${EDX_APPLICATION}".migrations

if check-marker "${migrate_marker}"; then
    echo "Migrations already complete for ${EDX_APPLICATION}. Skipping."
else
    cd "${EDX_PROJECT_DIR}"
    make migrate
    set-marker "${migrate_marker}"
fi

"${EDX_VENV}"/bin/gunicorn --pythonpath="${EDX_PROJECT_DIR}" -b 127.0.0.1:"${APPLICATION_PORT}" -w 2 --timeout=300  "${EDX_APPLICATION}".wsgi:application
