#!/usr/bin/env bash
set -e

dockerize -template /var/init_db.sql.template:/docker-entrypoint-initdb.d/init_db.sql

emit() {
    echo "$@" >&2
}

cnf_string=$(cat <<HERE
[client]
user=root
password=${MYSQL_ROOT_PASSWORD}
host=mysql
port=3306
HERE
)

reinit_db() {
    emit "Forcing initialization of the analytics MySQL database."
    dockerize -wait tcp://mysql:3306 -timeout 5s || { echo "Unable to connect to the database. Is it running?"; exit 1; }
    cat /docker-entrypoint-initdb.d/init_db.sql | mysql
}

if [[ -n "${IS_MYSQL_REINIT_JOB}" ]]; then
    cnf="${HOME}"/.my.cnf
    touch "${cnf}"
    chmod 600 "${cnf}"
    echo "${cnf_string}" >> "${cnf}"
    reinit_db
    emit "Finished database (re)initialization. Exiting."
    exit 0
fi

emit "Replacing current process with the MySQL docker entrypoint."
exec docker-entrypoint.sh "$@"
